### PR TITLE
Dsa in javascript card is created

### LINKED ISSUE #139: DSA in JavaScript Card is missing on Home page and Getting Started Page
### Description

# Description

Learn, Build & Hire Batch card is present on the main page and also on the getting started page. But DSA in JavaScript card is not there.

image

### PR DESCRIPTION
**Pull request by Shyam3050**
closes #139 

Screenshot (120)

Do you need to modify the title or description of a card?

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
You have to add DSA in JavaScript Card on Getting Started page too

image


And Always create new PR from new Branch. Now I can't merge your next branch too.

**Comment by Shyam3050** [comment]
@Vishal-raj-1 I will close this pull request after updating the "Getting Started" page. Then, I will create a new branch and raise a new pull request.

**Comment by Vishal-raj-1** [comment]
No need, Is baar ese hi krlo. Next time s dhyan dena

**Comment by Shyam3050** [comment]
Screenshot (122)



@Vishal-raj-1  I have a question about Github and Git. If I fork your project and clone it to my PC, how should I update it if you make changes?

**Review by Vishal-raj-1 — APPROVED** [review]

**Comment by Shyam3050** [comment]
@Vishal-raj-1  @ManishBisht777 
Screenshot (123)
deploy preview is not same as production

**Pull request merged**
