### PR TITLE
Updated loop content for DSA folder

### LINKED ISSUE #99: Update the Content of  Loops Page of DSA in JS
### Description

*Description:*
This issue is for updating the content of Loop Page of  DSA (Data Structures and Algorithms) section in our project. Here are the specific changes needed:

*1. What is on this Page ? - Section*
- It should contain the list of topics covered in the video.

*2. This Page should Contain Tabs - Learn and Assignment*
- Create tabs for "Learn" and "Assignment" sections.

*3. Learn Section should contain Video and Notes*
- In the "Learn" section, add subsections for videos and notes.

*4. Assignment section should contain assignments*
- In the "Assignment" section, include assignments related to the topics.

*5. To update the content*
Go to the Content folder of the root directory, then navigate to the batch folder, and then navigate to the DSA folder to make changes in the 'loops.mdx' file.

*Content Check:*
For reference, please check the current content in the [Loops Content](https://github.com/FrontendFreaks/DSA-in-JavaScript/blob/main/Basics/README.md) file.

*Additional Information:*
Please make sure to maintain consistency with the existing structure and style of the project. Let's enhance the DSA page to make it more user-friendly and informative.

### PR DESCRIPTION
**Pull request by nsundriyal62**
##Update the Content of Loops Page of DSA in JS
 Closes #99 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by nsundriyal62** [comment]
@sujitmemane sir

 check it out please
then i will going to solve other problems

**Comment by sujitmemane** [comment]
> @sujitmemane sir
> 
> check it out please then i will going to solve other problems
Please also attach screenshot , We are facing hosting issues here

**Comment by nsundriyal62** [comment]
ok sir

**Review by Vishal-raj-1 — CHANGES_REQUESTED** [review]
You have to copy the source code and practice questions from [DSA In JavaScript Repo](https://github.com/FrontendFreaks/DSA-in-JavaScript/tree/main/Basics)

**Comment by nsundriyal62** [comment]
should i copy entire source code in assignment section or
do you want anything else?
i am little bit in confusion

sir can you please explain a bit more
i just new to these github and all

**Pull request merged**
