### PR TITLE
removed video from assignment tab of HTML

### LINKED ISSUE #142: Remove Unclear with concept? Watch this component and video from Assignment tab
### Description

# Bug

Video and source code is already present on the Learn Tab. So it is unnecessary to add same content on different tab.

image

Remove this section from all the assignments pages.

### PR DESCRIPTION
**Pull request by Huzaifa785**
## Fixes Issue

Fixed #142 

## Changes proposed

- [✅] My code follows the code style of this project.
- [✅] My change requires changes to the documentation.
- [✅] I have updated the documentation accordingly.
- [✅] All new and existing tests passed.
- [✅] This PR does not contain plagiarized content.
- [✅] The title of my pull request is a short description of the requested changes.

## Screenshots
Screenshot 2023-10-05 at 8 54 10 PM

## Note to reviewers

I removed the video as described in the issue from the assignment tab.

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
Hey @Huzaifa785 You have to remove this section from all pages. Not only from HTML.

Also in description `[x]` you have to write `x` not ✅

**Comment by Huzaifa785** [comment]
> Hey @Huzaifa785 You have to remove this section from all pages. Not only from HTML.
> 
> Also in description `[x]` you have to write `x` not ✅

oh sorry for that, will remove it from all pages and also keep in mind to use `x` from next time.

Will update soon

**Comment by Vishal-raj-1** [comment]
@Huzaifa785 Any update? And Before working, make sure to pull all the changes from upstream master

**Comment by Huzaifa785** [comment]
> @Huzaifa785 Any update? And Before working, make sure to pull all the changes from upstream master

sorry for the delay, will update it in a few hours.

**Comment by Huzaifa785** [comment]
> > @Huzaifa785 Any update? And Before working, make sure to pull all the changes from upstream master
> 
> sorry for the delay, will update it in a few hours.

hey, I see someone has already removed it, because I just now pulled from upstream/master, and that section was not there on the assignments tab

**Comment by Vishal-raj-1** [comment]
> hey, I see someone has already removed it, because I just now pulled from upstream/master, and that section was not there on the assignments tab

Is it done for all pages? Could you please confirm it once

**Comment by Huzaifa785** [comment]
> > hey, I see someone has already removed it, because I just now pulled from upstream/master, and that section was not there on the assignments tab
> 
> Is it done for all pages? Could you please confirm it once

Yes, its done for all, I checked it.

**Pull request closed without merging**
