### PR TITLE
Updated Array page in DSA section 

### PR DESCRIPTION
**Pull request by ankit1296**
## Changes proposed
  - DSA option in sidebar

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

  - Content of video
  
image

  - Learn and Assignment Tabs
  
image

  - Learn tab content (video and code snippets) 
  
image

  - Assignment tab content (questions)
  
  
image

### CODE REVIEW

**Comment by Vishal-raj-1** [comment]
Hey @ankit1296 just wait for 1 or 2 day. @sujitmemane is adding structure of DSA in JavaScript Batch. Then I will merge this PR.

**Comment by sujitmemane** [comment]
@ankit1296 

Check Issue No #101

**Comment by Vishal-raj-1** [comment]
@ankit1296 share the screenshot too once done

**Comment by ankit1296** [comment]
@Vishal-raj-1  Updated PR with Array content and updated screenshots and PR name. can you please check.

**Comment by ankit1296** [comment]
@Vishal-raj-1  can you please check this

**Review by Vishal-raj-1 — APPROVED** [review]
Perfect

**Pull request merged**
